### ISSUE TITLE
Please allow me to ask about my error when I run your git hub repository STREDWES-SWELL code. 

### ISSUE THREAD

**Issue by hieutv85** [ggerardlatek/STREDWES-SWELL#1] opened 2024-02-28 04:22 UTC
Hi, 

Thank you very much for your GitHub repository. 
Please allow me to ask about the error I made when I ran your code. 

I think I set up everything correctly, as you mentioned in file /doc/preprocessing.md, which includes downloading all .S00 files to the specific directory and then using Matlab code to convert them to .mat file. I also used Google Colab. 

But when I run code to process the raw data subject, I have this problem (please look at the first picture). When I delete only [f"raw_pp{s}_c{c}"] at the end of line 12 of your code (scipy.io.loadmat command) then, I have another error (please have a look at the second picture). 

Line 12 : s_raw_c_part = scipy.io.loadmat(f"{input_data_dir}/s{s}_physio_raw.mat")[f"raw_pp{s}_c{c}"]
Line 12 after deleting: s_raw_c_part = scipy.io.loadmat(f"{input_data_dir}/s{s}_physio_raw.mat")

Please tell me how to fix these problems and read the SWELL dataset. 
Thank you very much. 

Picture 1
![picture1](https://github.com/ggerardlatek/STREDWES-SWELL/assets/34276013/9165c6f0-71d2-4aa5-8a3c-8df53eecee21)
Picture 2
![picture2](https://github.com/ggerardlatek/STREDWES-SWELL/assets/34276013/f0dad709-9a6f-42f5-bd18-6b7e1488f8d0)

**Comment by ggerardlatek** [comment] 2024-02-28 17:07
Hello @hieutv85 . Thank you for the feedback. We are looking into it, and we will provide an update as soon as we can replicate the issue.

**Comment by hieutv85** [comment] 2024-02-29 00:48
Thank you very much for your reply. Please help me handle the errors and load the SWELL dataset. I need your support.

**Comment by ggerardlatek** [comment] 2024-03-01 15:45
Hello @hieutv85 . I pushed a new version of the MATLAB scripts that convert the `.S00` files into `.mat` to be then read and processed in the notebook. Please, make sure that you have downloaded all the `.S00` files for all subjects. For each subject 3 files should be downloaded, e.g. `pp10_8-10-2012-c1.S00`, `pp10_8-10-2012-c2.S00` and `pp10_8-10-2012-c3.S00` for subject 10.
In the scripts I aligned the folder names to what is in the documentation. The `.S00` files must be placed in a folder named `Swell_DB_S00_raw` and the `.mat` files are going to be created in another folder named `dataset`.
I then checked that the `raw_ppX_cY` structs, with `X` is the subject id and `Y` the channel are present in each `.mat` file. You can also check it from within MATLAB by opening the `.mat` files generated by the scripts directly from MATLAB. If they are not then the issue is with the execution of the MATLAB scripts (make sure that you execute the scripts from the same folder where the two sub-folders `Swell_DB_S00_raw` and `dataset` are). I hope that solves the issue.

**Comment by hieutv85** [comment] 2024-03-04 05:41
Hi @ggerardlatek 

It works well after your changes. Thank you very much for supporting. I really appreciate your kind and fast support. 

Please allow me to ask you another question. I know that you discarded 9 participants out of 25 participants (participants with ID are 3, 8, 11, 15, 19, 20, 22, 23, 25). I also just want to look at and do some simple data analysis on the other 9 participants. However, errors happen when I load data from participants 8, 11 and 23. Could you please help me open these data or tell me how to do it? I have also attached pictures showing the errors; I used the same code but changed this part below to demand participants. 

_Code: subjects =[1,2,4,5,6,7,9,10,12,13,14,16,17,18,21,24]_

Participant 8
[
![SWELL participant 8](https://github.com/ggerardlatek/STREDWES-SWELL/assets/34276013/16f848d1-98c8-4d3f-b293-dfab0f180d7a)
](URL)

Participant 11
![SWELL participant 11](https://github.com/ggerardlatek/STREDWES-SWELL/assets/34276013/81a929b6-a0ad-4e7f-b9ee-b34440c6b528)

Participant 23
![SWELL participant 23](https://github.com/ggerardlatek/STREDWES-SWELL/assets/34276013/de8825e8-4f2d-45e7-a69f-28fa78a3edac)

Thank you very much. Please support me.

**Comment by ggerardlatek** [comment] 2024-03-05 07:22
Hello @hieutv85 . Thank you for confirming the issue is resolved. I will go ahead and close it then.

On your remark about subjects 8, 11 and 23 this is expected because, as reported in the file 'D - Physiology features (HR_HRV_SCL - final).csv', S8 and S11 have '999' in HR signal (missing data) while for subject 23 EDA data is not available.

**Closed as completed by ggerardlatek** 2024-03-05 07:22 UTC

**Comment by hieutv85** [comment] 2024-03-06 02:30
Thank you very much @ggerardlatek.

**Comment by hieutv85** [comment] 2024-03-12 01:28
Hi @ggerardlatek , could you please guide me on how to keep the original frequency (2048Hz) of the SWELL dataset? Please support me. Thank you very much. 
I tried to do it myself, but I still needed some help. 

When I changed the value of variable fdown from 32 to 2048, I got this issue from the resampling code part. 

![frequency](https://github.com/ggerardlatek/STREDWES-SWELL/assets/34276013/0ea2bff1-2f53-4947-93cd-fbbc9810e317)

issue: 
![issue1](https://github.com/ggerardlatek/STREDWES-SWELL/assets/34276013/5f9865b3-f477-414a-9c1c-60a0d215375a)


When I keep the value of fdown as 2048, comment on the resampling code part and modify the code to load the raw data. I think it can load the raw data, but I have this issue. 

![change1](https://github.com/ggerardlatek/STREDWES-SWELL/assets/34276013/07b368b0-1a0d-4ed1-94c5-f772c6781f8f)
![change2](https://github.com/ggerardlatek/STREDWES-SWELL/assets/34276013/b0cb002c-92b8-4ca4-9b6f-a2d0c39cdd00)

issue: 
![issue2](https://github.com/ggerardlatek/STREDWES-SWELL/assets/34276013/ea960329-35d9-4978-8160-872857759834)
